PCHR-2140: Add CONTRIBUTING.md
compucorp/org.civicrm.shoreditch pull request #12
Opened 2017-04-11 13:36 UTC by AkA84

#### IN PROGRESS

2017-04-12 12:30 UTC, meladawy requested changes

2017-04-12 12:30 UTC, meladawy commented on CONTRIBUTING.md
> +2. Please read the [README](https://github.com/compucorp/org.civicrm.shoreditch/blob/staging/README.md) to get an overview of what the theme is and how it works
I found some lines ends with "." but some others doesn't. please try to make it consistent

2017-04-12 12:30 UTC, meladawy commented on CONTRIBUTING.md
> +3. **Add a custom component** *(i.e., wizard component)* There are some component in CiviCRM that do not have any equivalent in the Bootstrap component library, and as such they have to be written fr
This also doesn't has "." at the end. just make it consistent with others

2017-04-12 12:30 UTC, meladawy commented on CONTRIBUTING.md
> +In order to make sure that your work does not introduce regression issues or unexpected changes, there are two tools that you are encouraged to use: [org.civicrm.styleguide](https://github.com/civicr
Do we need the "," before and? also ending the line with "." is preferred

2017-04-12 12:35 UTC, meladawy approved these changes

2017-04-12 20:57 UTC, totten commented
This is a good idea. :) I like the substance/topics being conveyed.

As a personal editorial opinion... I think of `CONTRIBUTING.md` as talking about Git/Github/JIRA workflow considerations. It might make sense to:
 * Split this into a couple files (`CODING.md` to discuss code-structure/design-guidelines/things-to-keep-in-mind; `TESTING.md` for the testing process; `CONTRIBUTING.md` for any Git/Github/JIRA workflow.)
 * Put hyperlinks in `README.md` and `CONTRIBUTING.md` to reference the other files.

The split is appealing for a few reasons:
 * When reading a new library, I often start from the README and want to understand the code-structure/design-guidelines first -- the idea of making a contribution hasn't crossed my mind yet.
 * The CONTRIBUTING.md is displayed in Github when you open a PR. At that point, they've already written a change Obviously, it's good to remind them about the general guidelines (because some people shoot from the hip), but their patience is fading, and a long doc will make their eyes glaze over.

However, those are just opinions -- if you look around at different FOSS projects, there's a variety of `CONTRIBUTING.md` styles, so I think you have a lot of discretion about writing it.

2017-04-13 07:59 UTC, AkA84 commented
hey @totten , thanks a lot for your feedback!

What I ended up doing is something in the middle, I split the content in three different files as you suggested, but left CONTRIBUTING.md as the "entry point" from the README for people who want to contribute to the project (as that seems the common pattern)

I also added a section about how to report bugs and suggest enhancement, and some simple Git commit message guidelines

Let me know what you think, thanks!

2017-04-13 09:34 UTC, meladawy approved these changes
I feel more comfortable about this splitting. I approve this.

2017-04-13 17:03 UTC, totten commented
Yeah, the split looks better, and I like how it moved the `npm`/`gulp` instructions to `CODING.md`.

2017-04-18 05:23 UTC, merged