PCHR-4356: Sync fork with latest release
compucorp/org.civicrm.shoreditch pull request #136
Opened 2018-10-31 16:55 UTC by AkA84

### IN PROGRESS

2018-11-02 10:37 UTC, igorpavlov-zz requested changes

2018-11-02 10:37 UTC, igorpavlov commented on info.xml
> +  <releaseDate>2018-10-29</releaseDate>
Just a question, this is sync and **not** a release, should we actually update these fields?

2018-11-02 10:56 UTC, igorpavlov-zz approved these changes

2018-11-02 15:17 UTC, igorpavlov-zz approved these changes

2018-11-05 11:49 UTC, deb1990 approved these changes

2018-11-05 13:03 UTC, merged