PCHR-2543: Override CiviCRM styles for Bootstrap migration
compucorp/org.civicrm.shoreditch pull request #31
Opened 2017-09-04 14:20 UTC by reneolivo

:warning: Under construction.

This changes override CiviCRM styles when wrapping templates inside a #bootstrap-theme tag. The mix between Bootstrap and CiviCRM make some components such as input, and selects to display in an undesired state.

2017-09-04 15:39 UTC, igorpavlov-zz requested changes

2017-09-04 15:39 UTC, igorpavlov commented on base/scss/overrides/reset/_civicrm.scss
> +// removes extra padding on select2 ul element added by bootstrap:
Could you please try the following:
1) Temporary remove these styles that fix the selector
2) Apply a class "no-select2" to the broken selector
What happens if you do it?

2017-09-04 16:46 UTC, igorpavlov commented
Please change the base branch to `staging` if your tests pass.

2017-09-04 16:53 UTC, igorpavlov-zz approved these changes

2017-09-04 16:54 UTC, igorpavlov commented
Please change the base branch to `staging` and merge to `staging`.

2017-09-04 17:31 UTC, igorpavlov commented
Approved.

2017-09-04 18:00 UTC, jamienovick commented
@reneolivo small point - but is that the correct icon for "add" leave and absence type? I think the icon should be a + or something?

2017-09-05 15:18 UTC, reneolivo commented
@jamienovick I find that icon odd as well, but it's the one that was being used before these changes. 
![screenshot 2017-09-05 11 17 22](https://user-images.githubusercontent.com/1642119/30068438-4bb5c400-920a-11e7-8779-0bd7d8e632f0.png)

The whole button is generated by CiviCRM, but I can try to hide it or even replace it using CSS. Should I do that?

2017-09-05 15:43 UTC, reneolivo commented
@jamienovick I have made the change:
![screenshot 2017-09-05 11 40 09](https://user-images.githubusercontent.com/1642119/30069555-7c744a14-920d-11e7-811b-64e00fbbe918.png)

Not sure what icon library was being used before, but it seems it's not working very well. The ^ symbol is the default icon, so this must be broken.

To fix it I added the following code:

```scss
// changes the add icon from ^ to +:
.icon.add-icon {
  background: none;

  &::before {
    content: '\f067';
    display: block;
    font-family: FontAwesome;
    text-indent: 0;
  }
}
```

`\f067` is the + symbol in font-awesome. This will change all add icons that are inside #bootstrap-theme so it won't change (or break) CiviCRM as a whole, but at least it will fix the pages that are being migrated to Bootstrap. Is that ok?

2017-09-05 15:46 UTC, jamienovick commented
Sounds good to me. So new bootstrap pages will work. I cant comment on the technical but outcome sounds good. thanks!!

2017-09-05 16:05 UTC, merged