Hw 262 new mailing schedule step
compucorp/org.civicrm.shoreditch pull request #5
Opened 2017-03-30 12:06 UTC by meladawy

Here is the changes : 
1- Define Wizard as a new crm component 
2- Change placeholder color for text fields 
3- Add rounded corner for panels as @jamienovick suggestion

![hw-262](https://cloud.githubusercontent.com/assets/2423218/24503336/ede893b4-1551-11e7-8ce6-4a40b4c37cb5.png)

2017-03-30 12:16 UTC, AkA84 requested changes
@meladawy you are defining a new component (`crm_wizard`), so in the PR please showcase its markup and a screenshot of what the result is. Like you would have for example in http://getbootstrap.com/components/#dropdowns-headers

2017-03-30 12:16 UTC, AkA84 commented on scss/bootstrap/overrides/style/_panel.scss
> +  border-radius: 2px;
in bootstrap i think there is a generic border-radius-related variable, shouldn't we use that?

2017-03-30 12:16 UTC, AkA84 commented on scss/bootstrap/overrides/style/_forms.scss
> +    &::-webkit-input-placeholder {
What's the need for all these browser-specific styles?

2017-03-30 12:16 UTC, AkA84 commented on scss/bootstrap/overrides/style/_panel.scss
> +  overflow: hidden;
Why is this needed?

2017-03-30 12:16 UTC, AkA84 commented on scss/bootstrap/components/_wizard.scss
>      margin-bottom: 30px;
Does this mean that any `.crm_wizard` will have a bottom margin?

2017-03-30 12:19 UTC, meladawy commented on scss/bootstrap/overrides/style/_panel.scss
> +  overflow: hidden;
Border radius is not applied to panels without having overflow hidden. not sure if there is any better approach

2017-03-30 12:22 UTC, meladawy commented on scss/bootstrap/overrides/style/_forms.scss
> +    &::-webkit-input-placeholder {
Shoudln't we support all the browsers?

2017-03-30 12:24 UTC, meladawy commented on scss/bootstrap/components/_wizard.scss
>      margin-bottom: 30px;
Yea this margin should be applied to any wizard. 

![wizard_margin](https://cloud.githubusercontent.com/assets/2423218/24503935/7b682784-1554-11e7-88bc-e26b4ff25dc1.png)

2017-03-30 13:06 UTC, meladawy commented on scss/bootstrap/overrides/style/_panel.scss
> +  overflow: hidden;
This overflow property required to git border-radius working...not sure if there is any better approach

2017-03-30 13:34 UTC, AkA84 requested changes

2017-03-30 13:34 UTC, AkA84 commented on scss/bootstrap/overrides/style/_forms.scss
> +    &::-webkit-input-placeholder {
apologies, i just realized that this being for the placeholder it requires vendor-specific selectors

2017-03-30 13:34 UTC, AkA84 commented on scss/bootstrap/overrides/style/_forms.scss
> +      /* Mozilla Firefox 4 to 18 */
this is not necessary, firefox is currently at v52

2017-03-30 13:34 UTC, AkA84 commented on scss/bootstrap/overrides/style/_forms.scss
> +      color: $crm-dark-grayblue;
Remove all these comments, it's evident enough what browser each selector is for, it's in the prefix

2017-03-30 13:34 UTC, AkA84 commented on scss/bootstrap/overrides/style/_panel.scss
> +  overflow: hidden;
yeah i think we need to discuss this

2017-03-30 15:45 UTC, meladawy commented on scss/bootstrap/overrides/style/_panel.scss
> +  overflow: hidden;
I removed the overflow hidden and replaced it with another border-radius in .panel-body

plz check this commit
https://github.com/compucorp/org.civicrm.shoreditch/pull/5/commits/2f1e119b5635437b3866ff1717d11edc78c27fca

2017-03-30 15:46 UTC, meladawy commented on scss/bootstrap/overrides/style/_forms.scss
> +      color: $crm-dark-grayblue;
Resolved 

https://github.com/compucorp/org.civicrm.shoreditch/pull/5/commits/a9b01d5fbb541333ceb876873f3544afcbfac9d2

2017-03-30 15:46 UTC, meladawy commented on scss/bootstrap/overrides/style/_forms.scss
> +      /* Mozilla Firefox 4 to 18 */
Resolved 
https://github.com/compucorp/org.civicrm.shoreditch/pull/5/commits/a9b01d5fbb541333ceb876873f3544afcbfac9d2

2017-03-31 11:36 UTC, meladawy commented
@AkA84 I removed radius from panels and added it to Wizard as per our yesterday discussion 
https://github.com/compucorp/org.civicrm.shoreditch/pull/5/commits/25198903dbd06147ffef1ab32d652eb6e88cf72a

2017-03-31 11:46 UTC, AkA84 approved these changes

2017-03-31 11:50 UTC, merged