PCHR-2609: Update main menu css
compucorp/org.civicrm.shoreditch pull request #53
Opened 2017-09-28 15:06 UTC by AkA84

## IN PROGRESS

2017-10-02 14:02 UTC, reneolivo requested changes

2017-10-02 14:02 UTC, reneolivo commented on scss/civicrm/main-menu/_main-menu.scss
> +    font-size: 13px;
font-size: [$font-size-base](https://github.com/compucorp/org.civicrm.shoreditch/blob/staging/scss/bootstrap/overrides/_variables.scss#L88)

2017-10-02 14:02 UTC, reneolivo commented on scss/civicrm/main-menu/_main-menu.scss
> +    font-size: 13px;
font-size: [$font-size-base](https://github.com/compucorp/org.civicrm.shoreditch/blob/staging/scss/bootstrap/overrides/_variables.scss#L88)

2017-10-02 14:02 UTC, reneolivo commented on scss/civicrm/main-menu/_main-menu.scss
> +      font-size: 13px;
font-size: [$font-size-base](https://github.com/compucorp/org.civicrm.shoreditch/blob/staging/scss/bootstrap/overrides/_variables.scss#L88)

2017-10-02 14:02 UTC, reneolivo commented on scss/civicrm/main-menu/_main-menu.scss
> +    font-size: 13px;
font-size: [$font-size-base](https://github.com/compucorp/org.civicrm.shoreditch/blob/staging/scss/bootstrap/overrides/_variables.scss#L88)

2017-10-02 14:02 UTC, reneolivo commented on scss/civicrm/main-menu/_main-menu.scss
> +      border-color: #D3DEE2;
border-color: [$crm-dark-grayblue](https://github.com/compucorp/org.civicrm.shoreditch/blob/staging/scss/bootstrap/overrides/_variables.scss#L67)
or
border-color: [$crm-dialog-container-border](https://github.com/compucorp/org.civicrm.shoreditch/blob/staging/scss/bootstrap/overrides/_variables.scss#L71)

2017-10-02 14:07 UTC, reneolivo approved these changes

2017-10-02 14:09 UTC, merged

2017-11-30 01:23 UTC, totten commented
The expanded padding on the menu is a pretty visible part of v0.1-alpha14.

Anecdotal feedback (from a long-term desktop user's perspective): the main menu bar feels pretty big, and the subnavs feel better. I'm not quite sure why the main nav feels big... there's no single objective benchmark for "big" or "small".  (Maybe the typical `btn` or `navbar` sizing is a reference?) 

Of course, you might get more people saying, "It's too small!" So just take that as one subjective data-point.

2017-12-01 01:34 UTC, totten commented
After using for a day, I really do like the subnavs!

2017-12-01 11:47 UTC, AkA84 commented
@totten is the taller main menu an acquired taste as well?

2017-12-05 22:27 UTC, totten commented
I haven't really acquired that taste yet. ;) Maybe if I switch from a desktop to a mobile device.