PCHR-2525: Remove Unwanted Styles
compucorp/org.civicrm.shoreditch pull request #65
Opened 2017-11-03 13:13 UTC by deb1990

2017-11-06 10:52 UTC, AkA84 commented
@deb1990 why do we have the problem with the extra line with the new icon but not with the old one?

2017-11-06 10:54 UTC, AkA84 requested changes

2017-11-06 10:54 UTC, AkA84 commented on scss/bootstrap/overrides/style/_ui-select.scss
> -    @include dropdown-arrow();
are we using this mixing anymore?

2017-11-06 10:54 UTC, AkA84 commented on scss/bootstrap/overrides/style/_ui-select.scss
> +    font-family: "FontAwesome";
i believe fontawesome already provides a mixing that does this

2017-11-06 10:54 UTC, AkA84 commented on scss/bootstrap/overrides/style/_ui-select.scss
> +    font-family: "FontAwesome";
also, not sure if we should consider putting this in a mixing like the old `dropdown-arrow`

2017-11-06 12:00 UTC, deb1990 commented on scss/bootstrap/overrides/style/_ui-select.scss
> -    @include dropdown-arrow();
No, removed.

2017-11-06 12:00 UTC, deb1990 commented on scss/bootstrap/overrides/style/_ui-select.scss
> +    font-family: "FontAwesome";
Done

2017-11-06 12:04 UTC, deb1990 commented
> @deb1990 why do we have the problem with the extra line with the new icon but not with the old one?

Previously the input was limited to 100px using css, that is why it was not reaching upto the drop down arrow, now as I removed the same, the width set by ui-select(inline width, using JS) is applied, but we also included the arrow, so there is not enough space for the input element, hence it is coming to the next line.

2017-11-06 13:35 UTC, igorpavlov commented
@deb1990 the extra line is what I fixed last time. I also made this field multiline. But as far as I can see it produced the problem with an unclickable area. The ideal solution would be making the input field (the real input) filling the whole rest width and have a min-width as well. This would require JS though.

2017-11-07 05:36 UTC, deb1990 commented
@igorpavlov Thanks for the tip, I fixed it using JS, now I focus on the input whenever the element is clicked. Refer https://github.com/civicrm/civihr/pull/2265

2017-11-07 08:00 UTC, AkA84 approved these changes

2017-11-07 08:10 UTC, merged