PCHR-2910: Fix notification tables
compucorp/org.civicrm.shoreditch pull request #90
Opened 2018-02-20 16:13 UTC by reneolivo

This PR fixes an issue where tables inside notifications have white text against the notification's white background rendering the text invisible.

### Before
![import contacts hr17 9000 2](https://user-images.githubusercontent.com/1642119/36434833-5f246b1c-1636-11e8-9b6b-509fae73411a.png)
* **Note**: the extra boder sticking out is because of an error in the template defined in CiviCRM:
https://github.com/civicrm/civicrm-core/blob/4.6/templates/CRM/Contact/Import/Form/DataSource.hlp#L97

### After
![import contacts hr17 9000 1](https://user-images.githubusercontent.com/1642119/36434765-36c7bf66-1636-11e8-84a5-2ffb75ef5eab.png)

2018-02-20 19:44 UTC, jamienovick commented
@reneolivo I think the table outlines shouldn't be shown at all? The SQL one for example isn't aligned correctly. best

2018-02-20 19:59 UTC, reneolivo commented
Hello @jamienovick this table is defined in a CiviCRM template for a particular notification. If we hide the outline for this table we would hide outlines for all tables (inside of notifications of course).

Also the SQL issue is because in their template they have something like this:

```html
<tr><td><code>SQL Example....</code><td></tr>
```
<small>Notice the last &lt;td&gt; is missing a /. <a href="https://github.com/civicrm/civicrm-core/blob/4.6/templates/CRM/Contact/Import/Form/DataSource.hlp#L97">Source here</a></small>

2018-02-20 20:06 UTC, reneolivo commented
Sent them a PR, doesn't follow any of their guidelines, but it's such a simple change, if they reject it they can implement it themselves:

https://github.com/civicrm/civicrm-core/pull/11698

2018-02-20 20:21 UTC, jamienovick commented
ok got it. I hadnt realised we had actual tables in the help bubbles and thought this was just being used instead of divs...

2018-02-21 06:22 UTC, AkA84 requested changes

2018-02-21 06:22 UTC, AkA84 commented on scss/civicrm/common/_notifications.scss
> +    table th {
```scss
table {
  td,
  th {
    // ...
  }
}

2018-02-21 08:55 UTC, AkA84 approved these changes

2018-02-22 11:18 UTC, merged